Fix cf2 path: patch to /mnt/SDCARD/Emus/tg5050/NDS.pak/drastic
The cf2 binary had /userdata/system/drastic embedded which caused
ERROR: Directory config file could not be loaded and eglChooseConfig
failure (0x3008). Patched to actual tg5050 install path.